In [2]:
import pandas as pd

movie = pd.read_csv('movie.csv')

movie

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [6]:
result = (
    (movie['imdb_score'] > 7) &
    (movie['content_rating'] == 'R') &
    (movie['actor_1_facebook_likes'] > 500) &
    (movie['title_year'] > 2010)
)

movie[result]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
128,Color,George Miller,739.0,120.0,750.0,943.0,Charlize Theron,27000.0,153629485.0,Action|Adventure|Sci-Fi|Thriller,...,1588.0,English,Australia,R,150000000.0,2015.0,9000.0,8.1,2.35,191000
178,Color,Alejandro G. Iñárritu,556.0,156.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,...,1188.0,English,USA,R,135000000.0,2015.0,27000.0,8.1,2.35,190000
293,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,1193.0,English,USA,R,100000000.0,2012.0,11000.0,8.5,2.35,199000
304,Color,Martin Scorsese,606.0,240.0,17000.0,4000.0,Matthew McConaughey,29000.0,116866727.0,Biography|Comedy|Crime|Drama,...,1138.0,English,USA,R,100000000.0,2013.0,11000.0,8.2,2.35,138000
307,Color,Tom Tykwer,511.0,172.0,670.0,1000.0,Jim Sturgess,15000.0,27098580.0,Drama|Sci-Fi,...,828.0,English,Germany,R,102000000.0,2012.0,5000.0,7.5,2.35,124000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4260,Color,Jamal Hill,10.0,89.0,47.0,585.0,Adam Ratcliffe,628.0,444044.0,Drama,...,19.0,English,USA,R,1900000.0,2015.0,606.0,7.2,1.85,1000
4422,Color,Gareth Evans,481.0,102.0,338.0,60.0,Yayan Ruhian,1000.0,4105123.0,Action|Crime|Thriller,...,316.0,Indonesian,Indonesia,R,1100000.0,2011.0,342.0,7.6,1.85,51000
4476,Color,Mike Cahill,140.0,106.0,135.0,11.0,Cara Seymour,7000.0,334658.0,Drama|Romance|Sci-Fi,...,160.0,English,USA,R,NaN,2014.0,71.0,7.3,2.39,32000
4543,Color,Tommy Oliver,6.0,90.0,66.0,734.0,Ruby Dee,904.0,NaN,Drama,...,3.0,English,USA,R,1000000.0,2013.0,782.0,7.1,NaN,181
4677,Color,Jeremy Saulnier,279.0,90.0,57.0,92.0,Eve Plumb,1000.0,258113.0,Crime|Drama|Thriller,...,135.0,English,USA,R,1066167.0,2013.0,235.0,7.1,2.35,0