In [1]:
import pandas as pd

data = pd.read_csv('ibm.csv')

data

             Date       Open       High        Low      Close        Volume
0      1962-01-02    5.04610    5.04610    4.98716    4.98716  5.935630e+05
1      1962-01-03    4.98716    5.03292    4.98716    5.03292  4.451750e+05
2      1962-01-04    5.03292    5.03292    4.98052    4.98052  3.995136e+05
3      1962-01-05    4.97389    4.97389    4.87511    4.88166  5.593215e+05
4      1962-01-08    4.88166    4.88166    4.75059    4.78972  8.332738e+05
...           ...        ...        ...        ...        ...           ...
15541  2023-10-05  140.90000  141.70000  140.19000  141.52000  3.223910e+06
15542  2023-10-06  141.40000  142.94000  140.11000  142.03000  3.511347e+06
15543  2023-10-09  142.30000  142.40000  140.68000  142.20000  2.354396e+06
15544  2023-10-10  142.60000  143.41500  141.72000  142.11000  3.015784e+06
15545  2023-10-11  142.51000  143.34000  142.14000  143.23000  2.511459e+06

[15546 rows x 6 columns]

In [4]:
def dfValueStatus(series):
    if series < 50:
        return "Juda past narx"
    elif 50 <= series <= 100:
        return "O'rtacha narx"
    else:
        return "Yuqori narx"
    
data["Status"] = data["Close"].apply(dfValueStatus)

data

,Date,Open,High,Low,Close,Volume,Status
0,1962-01-02,5.04610,5.04610,4.98716,4.98716,5.935630e+05,Juda past narx
1,1962-01-03,4.98716,5.03292,4.98716,5.03292,4.451750e+05,Juda past narx
2,1962-01-04,5.03292,5.03292,4.98052,4.98052,3.995136e+05,Juda past narx
3,1962-01-05,4.97389,4.97389,4.87511,4.88166,5.593215e+05,Juda past narx
4,1962-01-08,4.88166,4.88166,4.75059,4.78972,8.332738e+05,Juda past narx
...,...,...,...,...,...,...,...
15541,2023-10-05,140.90000,141.70000,140.19000,141.52000,3.223910e+06,Yuqori narx
15542,2023-10-06,141.40000,142.94000,140.11000,142.03000,3.511347e+06,Yuqori narx
15543,2023-10-09,142.30000,142.40000,140.68000,142.20000,2.354396e+06,Yuqori narx
15544,2023-10-10,142.60000,143.41500,141.72000,142.11000,3.015784e+06,Yuqori narx
15545,2023-10-11,142.51000,143.34000,142.14000,143.23000,2.511459e+06,Yuqori narx