## Pandas-3 (Grouping)

In [1]:
import pandas as pd
import numpy as np

In [3]:
flights = pd.read_csv('data/flights.csv')
flights

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58487,12,31,4,AA,SFO,DFW,515,5.0,166.0,1464,1045,-19.0,0,0
58488,12,31,4,F9,LAS,SFO,1910,13.0,71.0,414,2050,4.0,0,0
58489,12,31,4,OO,SFO,SBA,1846,-6.0,46.0,262,1956,-5.0,0,0
58490,12,31,4,WN,MSP,ATL,525,39.0,124.0,907,855,34.0,0,0
58491,12,31,4,OO,SFO,BOI,859,5.0,73.0,522,1146,-1.0,0,0

In [5]:
flights[flights['DEST_AIR'] == 'SLC']

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
51,1,1,4,OO,PHX,SLC,950,NaN,NaN,507,1138,NaN,0,1
82,1,1,4,OO,LAX,SLC,1940,-5.0,98.0,590,2225,23.0,0,0
222,1,2,5,DL,LAX,SLC,725,9.0,90.0,590,1019,7.0,0,0
433,1,3,6,DL,ATL,SLC,1205,0.0,215.0,1590,1424,-24.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58189,12,30,3,WN,PHX,SLC,600,1.0,76.0,507,735,0.0,0,0
58368,12,31,4,AA,PHX,SLC,1440,8.0,70.0,507,1620,-4.0,0,0
58374,12,31,4,DL,LAX,SLC,1020,1.0,79.0,590,1310,-14.0,0,0
58381,12,31,4,OO,SFO,SLC,1918,-5.0,80.0,599,2209,-7.0,0,0
58404,12,31,4,AS,SFO,SLC,2110,-2.0,80.0,599,2358,-4.0,0,0

In [6]:
flights[flights['DEST_AIR'].eq('SLC')]

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
51,1,1,4,OO,PHX,SLC,950,NaN,NaN,507,1138,NaN,0,1
82,1,1,4,OO,LAX,SLC,1940,-5.0,98.0,590,2225,23.0,0,0
222,1,2,5,DL,LAX,SLC,725,9.0,90.0,590,1019,7.0,0,0
433,1,3,6,DL,ATL,SLC,1205,0.0,215.0,1590,1424,-24.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58189,12,30,3,WN,PHX,SLC,600,1.0,76.0,507,735,0.0,0,0
58368,12,31,4,AA,PHX,SLC,1440,8.0,70.0,507,1620,-4.0,0,0
58374,12,31,4,DL,LAX,SLC,1020,1.0,79.0,590,1310,-14.0,0,0
58381,12,31,4,OO,SFO,SLC,1918,-5.0,80.0,599,2209,-7.0,0,0
58404,12,31,4,AS,SFO,SLC,2110,-2.0,80.0,599,2358,-4.0,0,0

In [7]:
flights.groupby('AIRLINE')

In [8]:
list(flights.groupby('AIRLINE'))

[('AA',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  3          1    1        4      AA     DFW      DCA       1555        7.0
  6          1    1        4      AA     DFW      MSY       1250       84.0
  8          1    1        4      AA     ORD      STL       1845       -5.0
  15         1    1        4      AA     DEN      DFW       1445       -6.0
  26         1    1        4      AA     LAX      AUS       1430       33.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58470     12   31        4      AA     DFW      FAT       1020       -3.0
  58475     12   31        4      AA     IAH      CLT        710        1.0
  58476     12   31        4      AA     DFW      TPA       1020       -3.0
  58479     12   31        4      AA     DFW      ELP       1200        3.0
  58487     12   31        4      AA     SFO      DFW        515        5.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  3         126.0  1192       1935       -7.0         0          0
  6          64.0   447       1410       83.0         0          0
  8          44.0   258       1950       -5.0         0          0
  15         93.0   641       1745        4.0         0          0
  26        157.0  1242       1925       41.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58470     196.0  1313       1156       -2.0         0          0
  58475     113.0   912       1037      -12.0         0          0
  58476     121.0   929       1340       -6.0         0          0
  58479      94.0   551       1250       13.0         0          0
  58487     166.0  1464       1045      -19.0         0          0

  [8900 rows x 14 columns]),
 ('AS',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  38         1    1        4      AS     PHX      SEA       1505       -2.0
  198        1    2        5      AS     LAX      SEA       2110        5.0
  241        1    2        5      AS     LAS      PDX        650       -5.0
  277        1    2        5      AS     ORD      ANC        935       -1.0
  397        1    3        6      AS     LAS      SEA       1300       48.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58305     12   30        3      AS     LAX      SEA       1325       -2.0
  58355     12   31        4      AS     PHX      SEA       1200       -5.0
  58404     12   31        4      AS     SFO      SLC       2110       -2.0
  58407     12   31        4      AS     SFO      PDX        645       -2.0
  58428     12   31        4      AS     LAX      SEA       1420       -8.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  38        155.0  1107       1702       -3.0         0          0
  198       145.0   954       2352        8.0         0          0
  241       117.0   763        906       -3.0         0          0
  277       402.0  2846       1339       -6.0         0          0
  397       137.0   867       1535       47.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58305     134.0   954       1608       -7.0         0          0
  58355     145.0  1107       1407      -24.0         0          0
  58404      80.0   599       2358       -4.0         0          0
  58407      81.0   550        832       -3.0         0          0
  58428     127.0   954       1709      -25.0         0          0

  [768 rows x 14 columns]),
 ('B6',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  123        1    1        4      B6     LAS      BOS       1230        0.0
  127        1    1        4      B6     LAS      BOS       2359       68.0
  239        1    2        5      B6     ORD      BOS        540       -8.0
  333        1    3        6      B6     LAX      FLL       2237       32.0
  548        1    4        7      B6     SFO      FLL       2307       -4.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58262     12   30        3      B6     SFO      LGB       1921       -6.0
  58301     12   30        3      B6     LAX      JFK        630        4.0
  58425     12   31        4      B6     ORD      SJU        700      239.0
  58477     12   31        4      B6     DFW      BOS       1145       12.0
  58483     12   31        4      B6     PHX      BOS       2236      -12.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  123       246.0  2381       2026      -27.0         0          0
  127       247.0  2381        749       46.0         0          0
  239        96.0   867        856      -22.0         0          0
  333       270.0  2342        619       42.0         0          0
  548       298.0  2583        724       -1.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58262      57.0   354       2038      -14.0         0          0
  58301     285.0  2475       1445       -6.0         0          0
  58425     250.0  2072       1335      239.0         0          0
  58477     161.0  1562       1608      -14.0         0          0
  58483     231.0  2300        515      -45.0         0          0

  [543 rows x 14 columns]),
 ('DL',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  53         1    1        4      DL     LAS      MSP        713       -5.0
  57         1    1        4      DL     MSP      RSW        700       -1.0
  77         1    1        4      DL     LAX      ATL       1130       24.0
  79         1    1        4      DL     LAX      CMH       2146       -3.0
  85         1    1        4      DL     ATL      OKC       2059       -4.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58440     12   31        4      DL     ATL      CVG       1611       -4.0
  58448     12   31        4      DL     ATL      SRQ       1610        0.0
  58464     12   31        4      DL     LAX      SFO        700      108.0
  58467     12   31        4      DL     ATL      IND       1235       -3.0
  58485     12   31        4      DL     ATL      CMH       2206        2.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  53        156.0  1299       1220      -18.0         0          0
  57        169.0  1416       1130      -20.0         0          0
  77        217.0  1947       1840       16.0         0          0
  79        223.0  1995        459      -13.0         0          0
  85        116.0   761       2227      -12.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58440      61.0   373       1736       -6.0         0          0
  58448      61.0   444       1740      -13.0         0          0
  58464      54.0   337        825      105.0         0          0
  58467      63.0   432       1407      -13.0         0          0
  58485      64.0   447       2338       -8.0         0          0

  [10601 rows x 14 columns]),
 ('EV',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  11         1    1        4      EV     ORD      JAN       1155        6.0
  13         1    1        4      EV     ORD      CMH       1010       -2.0
  29         1    1        4      EV     ORD      IND       1025       -6.0
  40         1    1        4      EV     IAH      CLE       1038       -3.0
  69         1    1        4      EV     ATL      RAP       1930       -5.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58445     12   31        4      EV     DFW      TXK        850       -5.0
  58452     12   31        4      EV     DFW      SHV       1650       -4.0
  58459     12   31        4      EV     MSP      ORD       1435       18.0
  58463     12   31        4      EV     ORD      MSN       1220       18.0
  58486     12   31        4      EV     DFW      LFT        850       21.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  11        113.0   677       1403        5.0         0          0
  13         46.0   296       1228       -9.0         0          0
  29         29.0   177       1228      -19.0         0          0
  40        126.0  1091       1425      -18.0         0          0
  69        181.0  1230       2104      -15.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58445      30.0   181        948      -17.0         0          0
  58452      32.0   190       1746      -12.0         0          0
  58459      61.0   334       1609        3.0         0          0
  58463      32.0   108       1319       27.0         0          0
  58486      52.0   351       1012       14.0         0          0

  [5858 rows x 14 columns]),
 ('F9',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  7          1    1        4      F9     SFO      PHX       1020       -7.0
  93         1    1        4      F9     ATL      DEN        859       16.0
  209        1    2        5      F9     MSP      DEN       1025       -6.0
  232        1    2        5      F9     DEN      PHX       2040       -7.0
  247        1    2        5      F9     ORD      ATL        730       10.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58288     12   30        3      F9     DEN      ORD        625       -4.0
  58331     12   30        3      F9     ORD      PHX        825       18.0
  58447     12   31        4      F9     DEN      LAS       1245       13.0
  58449     12   31        4      F9     DEN      MCO        645       11.0
  58488     12   31        4      F9     LAS      SFO       1910       13.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  7          91.0   651       1315       -6.0         0          0
  93        181.0  1199       1026       10.0         0          0
  209        97.0   680       1134      -13.0         0          0
  232        83.0   602       2228      -18.0         0          0
  247        86.0   606       1020       23.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58288     136.0   888       1000       14.0         0          0
  58331     207.0  1440       1127       14.0         0          0
  58447      94.0   628       1340       13.0         0          0
  58449     169.0  1546       1224      -11.0         0          0
  58488      71.0   414       2050        4.0         0          0

  [1317 rows x 14 columns]),
 ('HA',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  582        1    4        7      HA     LAX      OGG       1115      -11.0
  712        1    5        1      HA     LAS      HNL        900       -5.0
  878        1    6        2      HA     PHX      HNL        800        1.0
  1053       1    7        3      HA     LAX      HNL       1705        0.0
  1269       1    8        4      HA     LAX      HNL       1000       -1.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  55883     12   16        3      HA     LAX      HNL        835        1.0
  56174     12   18        5      HA     LAX      HNL        835       -5.0
  56350     12   19        6      HA     PHX      HNL        800       -5.0
  56816     12   21        1      HA     LAX      LIH        740       20.0
  58391     12   31        4      HA     LAX      HNL       1000        0.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  582       310.0  2486       1500      -27.0         0          0
  712       357.0  2762       1315        5.0         0          0
  878       374.0  2917       1140        3.0         0          0
  1053      332.0  2556       2055       -2.0         0          0
  1269      335.0  2556       1350        0.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  55883     314.0  2556       1235      -18.0         0          0
  56174     342.0  2556       1235       -4.0         0          0
  56350     363.0  2917       1155      -34.0         0          0
  56816     303.0  2615       1145      -11.0         0          0
  58391     324.0  2556       1350       -9.0         0          0

  [112 rows x 14 columns]),
 ('MQ',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  2          1    1        4      MQ     DFW      VPS       1305       36.0
  10         1    1        4      MQ     DFW      DRO       1335       28.0
  18         1    1        4      MQ     ORD      DAY       2220       19.0
  24         1    1        4      MQ     DFW      BTR        730        NaN
  50         1    1        4      MQ     ORD      CID       1135       -7.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58415     12   31        4      MQ     ORD      FWA        845       -2.0
  58426     12   31        4      MQ     DFW      FAR       1154        4.0
  58468     12   31        4      MQ     DFW      OKC       1720       -3.0
  58474     12   31        4      MQ     ORD      FNT        829        4.0
  58484     12   31        4      MQ     ORD      DSM       1333        1.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  2          85.0   641       1453       35.0         0          0
  10        104.0   674       1438       28.0         0          0
  18         37.0   240         23       20.0         0          0
  24          NaN   383        853        NaN         0          1
  50         37.0   196       1238      -15.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58415      37.0   157       1045       -4.0         0          0
  58426     124.0   968       1437      -13.0         0          0
  58468      31.0   175       1819      -10.0         0          0
  58474      40.0   223       1034       -4.0         0          0
  58484      57.0   299       1455       -7.0         0          0

  [3471 rows x 14 columns]),
 ('NK',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  17         1    1        4      NK     DEN      DTW       1952       37.0
  74         1    1        4      NK     PHX      DFW        159       -1.0
  95         1    1        4      NK     LAS      OAK       1115       22.0
  109        1    1        4      NK     MSP      ORD        616        2.0
  166        1    2        5      NK     LAS      PDX       1535       -8.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58160     12   29        2      NK     MSP      MCO        740        0.0
  58197     12   30        3      NK     IAH      ORD        755       -8.0
  58437     12   31        4      NK     ORD      DFW       1952       15.0
  58461     12   31        4      NK     ORD      LGA       1801       -5.0
  58469     12   31        4      NK     LAS      MSY       1950      124.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  17        124.0  1123         31       54.0         0          0
  74        103.0   868        502        1.0         0          0
  95         62.0   407       1246       10.0         0          0
  109        49.0   334        745      -19.0         0          0
  166       123.0   763       1754       -4.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58160     171.0  1310       1158       33.0         0          0
  58197     136.0   925       1030       -2.0         0          0
  58437     135.0   802       2225       23.0         0          0
  58461      84.0   733       2109      -26.0         0          0
  58469     163.0  1500        112      101.0         0          0

  [1516 rows x 14 columns]),
 ('OO',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  12         1    1        4      OO     ORD      MSP       1510        2.0
  16         1    1        4      OO     DEN      SGU       1105       21.0
  22         1    1        4      OO     LAS      LAX       1544       -4.0
  25         1    1        4      OO     ORD      SPI       2110       -4.0
  27         1    1        4      OO     IAH      JAC       1104       -1.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58451     12   31        4      OO     ATL      FWA       1905       -3.0
  58480     12   31        4      OO     MSP      BIS       1310       -2.0
  58482     12   31        4      OO     DEN      CPR       1850       -2.0
  58489     12   31        4      OO     SFO      SBA       1846       -6.0
  58491     12   31        4      OO     SFO      BOI        859        5.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  12         65.0   334       1646        4.0         0          0
  16         66.0   517       1249       20.0         0          0
  22         39.0   236       1655      -12.0         0          0
  25         31.0   174       2205        5.0         0          0
  27        161.0  1265       1316       -1.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58451      72.0   508       2051      -14.0         0          0
  58480      65.0   386       1449       -9.0         0          0
  58482      38.0   230       1956        1.0         0          0
  58489      46.0   262       1956       -5.0         0          0
  58491      73.0   522       1146       -1.0         0          0

  [6588 rows x 14 columns]),
 ('UA',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  1          1    1        4      UA     DEN      IAD        823        7.0
  5          1    1        4      UA     IAH      SAN       1450        1.0
  9          1    1        4      UA     IAH      SJC        925        3.0
  14         1    1        4      UA     IAH      IND       1426       -1.0
  21         1    1        4      UA     ORD      CLE       2102       48.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  58422     12   31        4      UA     DEN      SAN       1535        0.0
  58432     12   31        4      UA     ORD      SAN       1915        7.0
  58457     12   31        4      UA     ORD      LAX        659       -1.0
  58460     12   31        4      UA     SFO      PHL       2235       -6.0
  58481     12   31        4      UA     IAH      LAX       1433        1.0

         AIR_TIME  DIST  SCHED_ARR  ARR_DELAY  DIVERTED  CANCELLED
  1         154.0  1452       1333      -13.0         0          0
  5         178.0  1303       1620      -14.0         0          0
  9         215.0  1608       1136      -14.0         0          0
  14        102.0   844       1742      -20.0         0          0
  21         47.0   315       2320       41.0         0          0
  ...         ...   ...        ...        ...       ...        ...
  58422     124.0   853       1704      -13.0         0          0
  58432     238.0  1723       2143       -3.0         0          0
  58457     241.0  1744        946        0.0         0          0
  58460     265.0  2521        700      -42.0         0          0
  58481     197.0  1379       1625      -13.0         0          0

  [7792 rows x 14 columns]),
 ('US',
         MONTH  DAY  WEEKDAY AIRLINE ORG_AIR DEST_AIR  SCHED_DEP  DEP_DELAY  \
  31         1    1        4      US     PHX      DEN       1810       29.0
  35         1    1        4      US     ORD      PHL       1600       -2.0
  49         1    1        4      US     IAH      PHX       1445       -1.0
  96         1    1        4      US     ATL      PHL       1445       -4.0
  104        1    1        4      US     MSP      PHX        730       -3.0
  ...      ...  ...      ...     ...     ...      ...        ...        ...
  31514      6   30        2      US     DEN      PHL        705       -4.0

In [11]:
flights.groupby('AIRLINE').agg('min')

,MONTH,DAY,WEEKDAY,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
AIRLINE,,,,,,,,,,,,,
AA,1,1,1,ATL,ABQ,5,-15.0,29.0,175,1,-60.0,0,0
AS,1,1,1,ATL,ANC,600,-22.0,58.0,421,1,-57.0,0,0
B6,1,1,1,DEN,BOS,540,-19.0,40.0,231,7,-51.0,0,0
DL,1,1,1,ATL,ABE,5,-17.0,22.0,106,1,-57.0,0,0
EV,1,1,1,ATL,ABE,600,-17.0,14.0,74,2,-39.0,0,0
F9,1,1,1,ATL,ATL,5,-19.0,55.0,373,5,-43.0,0,0
HA,1,1,1,LAS,HNL,145,-24.0,281.0,2338,500,-44.0,0,0
MQ,1,1,1,ATL,ABI,500,-12.0,16.0,89,3,-37.0,0,0
NK,1,1,1,ATL,ACY,5,-16.0,39.0,236,5,-39.0,0,0
OO,1,1,1,ATL,ABQ,7,-20.0,8.0,67,1,-44.0,0,0
UA,1,1,1,ATL,ABQ,7,-18.0,23.0,108,1,-58.0,0,0
US,1,1,1,ATL,ANC,11,-15.0,36.0,226,2,-51.0,0,0
VX,1,1,1,LAS,AUS,10,-13.0,39.0,236,125,-51.0,0,0
WN,1,1,1,ATL,ABQ,515,-14.0,30.0,197,5,-52.0,0,0

In [12]:
flights.groupby('AIRLINE')[['WEEKDAY', 'ORG_AIR', 'DEST_AIR']].agg('min')

         WEEKDAY ORG_AIR DEST_AIR
AIRLINE
AA             1     ATL      ABQ
AS             1     ATL      ANC
B6             1     DEN      BOS
DL             1     ATL      ABE
EV             1     ATL      ABE
F9             1     ATL      ATL
HA             1     LAS      HNL
MQ             1     ATL      ABI
NK             1     ATL      ACY
OO             1     ATL      ABQ
UA             1     ATL      ABQ
US             1     ATL      ANC
VX             1     LAS      AUS
WN             1     ATL      ABQ

In [ ]:
flights.groupby('AIRLINE').agg({"WEEKDAY":'min'})   # resul dataframe da

         WEEKDAY
AIRLINE
AA             1
AS             1
B6             1
DL             1
EV             1
F9             1
HA             1
MQ             1
NK             1
OO             1
UA             1
US             1
VX             1
WN             1

In [ ]:
flights.groupby('AIRLINE')['WEEKDAY'].min() # natijasi Series boladi

AIRLINE
AA    1
AS    1
B6    1
DL    1
EV    1
F9    1
HA    1
MQ    1
NK    1
OO    1
UA    1
US    1
VX    1
WN    1
Name: WEEKDAY, dtype: int64

In [30]:
flights.groupby('AIRLINE').agg({"ARR_DELAY":'mean'}).reset_index()

   AIRLINE  ARR_DELAY
0       AA   5.542661
1       AS  -0.833333
2       B6   8.692593
3       DL   0.339691
4       EV   7.034580
5       F9  13.630651
6       HA   4.972973
7       MQ   6.860591
8       NK  18.436070
9       OO   7.593463
10      UA   7.765755
11      US   1.681105
12      VX   5.348884
13      WN   6.397353

In [ ]:
flights.groupby(['AIRLINE', 'WEEKDAY']).agg({"ARR_DELAY":'mean'}).reset_index() # indexni oddiy column qilib beradi

   AIRLINE  WEEKDAY  ARR_DELAY
0       AA        1   9.135772
1       AA        2   3.009053
2       AA        3   2.979561
3       AA        4   6.474771
4       AA        5   6.743017
..     ...      ...        ...
93      WN        3   5.370518
94      WN        4   8.524800
95      WN        5   6.722781
96      WN        6   2.449692
97      WN        7   6.398601

[98 rows x 3 columns]

In [36]:
test = flights.groupby('AIRLINE').agg({"ARR_DELAY":'mean'}).reset_index()

In [41]:
test.set_index('AIRLINE', inplace=True)

In [42]:
test

         ARR_DELAY
AIRLINE
AA        5.542661
AS       -0.833333
B6        8.692593
DL        0.339691
EV        7.034580
F9       13.630651
HA        4.972973
MQ        6.860591
NK       18.436070
OO        7.593463
UA        7.765755
US        1.681105
VX        5.348884
WN        6.397353

In [43]:
flights

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58487,12,31,4,AA,SFO,DFW,515,5.0,166.0,1464,1045,-19.0,0,0
58488,12,31,4,F9,LAS,SFO,1910,13.0,71.0,414,2050,4.0,0,0
58489,12,31,4,OO,SFO,SBA,1846,-6.0,46.0,262,1956,-5.0,0,0
58490,12,31,4,WN,MSP,ATL,525,39.0,124.0,907,855,34.0,0,0
58491,12,31,4,OO,SFO,BOI,859,5.0,73.0,522,1146,-1.0,0,0

In [48]:
flights.groupby('AIRLINE').agg({"ARR_DELAY":'mean', "CANCELLED":'count'})

         ARR_DELAY  CANCELLED
AIRLINE
AA        5.542661       8900
AS       -0.833333        768
B6        8.692593        543
DL        0.339691      10601
EV        7.034580       5858
F9       13.630651       1317
HA        4.972973        112
MQ        6.860591       3471
NK       18.436070       1516
OO        7.593463       6588
UA        7.765755       7792
US        1.681105       1615
VX        5.348884        993
WN        6.397353       8418

In [ ]:
flights.groupby('AIRLINE').agg({"ARR_DELAY": np.mean, "CANCELLED":'count'})

         ARR_DELAY  CANCELLED
AIRLINE
AA        5.542661       8900
AS       -0.833333        768
B6        8.692593        543
DL        0.339691      10601
EV        7.034580       5858
F9       13.630651       1317
HA        4.972973        112
MQ        6.860591       3471
NK       18.436070       1516
OO        7.593463       6588
UA        7.765755       7792
US        1.681105       1615
VX        5.348884        993
WN        6.397353       8418

In [49]:
flights

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58487,12,31,4,AA,SFO,DFW,515,5.0,166.0,1464,1045,-19.0,0,0
58488,12,31,4,F9,LAS,SFO,1910,13.0,71.0,414,2050,4.0,0,0
58489,12,31,4,OO,SFO,SBA,1846,-6.0,46.0,262,1956,-5.0,0,0
58490,12,31,4,WN,MSP,ATL,525,39.0,124.0,907,855,34.0,0,0
58491,12,31,4,OO,SFO,BOI,859,5.0,73.0,522,1146,-1.0,0,0

In [52]:
flights.groupby('AIRLINE')\
    .agg({"ARR_DELAY": np.mean, "CANCELLED":'count', 'SCHED_ARR':'mean'})

         ARR_DELAY  CANCELLED    SCHED_ARR
AIRLINE
AA        5.542661       8900  1546.960899
AS       -0.833333        768  1548.292969
B6        8.692593        543  1432.889503
DL        0.339691      10601  1578.735402
EV        7.034580       5858  1571.798054
F9       13.630651       1317  1510.177677
HA        4.972973        112  1280.714286
MQ        6.860591       3471  1587.835494
NK       18.436070       1516  1398.226913
OO        7.593463       6588  1573.730267
UA        7.765755       7792  1532.871150
US        1.681105       1615  1489.131269
VX        5.348884        993  1581.023162
WN        6.397353       8418  1532.243407

In [57]:
flights.groupby(['AIRLINE', 'WEEKDAY'])[['CANCELLED']].sum()

                 CANCELLED
AIRLINE WEEKDAY
AA      1               41
        2                9
        3               16
        4               20
        5               18
...                    ...
WN      3               18
        4               10
        5                7
        6               10
        7                7

[98 rows x 1 columns]

In [58]:
flights.groupby(['AIRLINE', 'WEEKDAY']).agg({'CANCELLED':'sum'})

                 CANCELLED
AIRLINE WEEKDAY
AA      1               41
        2                9
        3               16
        4               20
        5               18
...                    ...
WN      3               18
        4               10
        5                7
        6               10
        7                7

[98 rows x 1 columns]

In [ ]:
# har bir airline va weekday boyicha
# cancelled min, max, count,
# diverted mean, max, sum

In [61]:
a = flights.groupby(['AIRLINE', 'WEEKDAY'])\
    .agg({'CANCELLED':['min', 'max', 'count'], 'DIVERTED':['mean', 'max', 'sum']})

In [67]:
a

                CANCELLED            DIVERTED
                      min max count      mean max sum
AIRLINE WEEKDAY
AA      1               0   1  1277  0.004699   1   6
        2               0   1  1226  0.001631   1   2
        3               0   1  1339  0.001494   1   2
        4               0   1  1333  0.003751   1   5
        5               0   1  1272  0.000786   1   1
...                   ...  ..   ...       ...  ..  ..
WN      3               0   1  1275  0.001569   1   2
        4               0   1  1264  0.003165   1   4
        5               0   1  1201  0.000000   0   0
        6               0   1   987  0.003040   1   3
        7               0   1  1154  0.002600   1   3

[98 rows x 6 columns]

In [72]:
a.columns

MultiIndex([('CANCELLED',   'min'),
            ('CANCELLED',   'max'),
            ('CANCELLED', 'count'),
            ( 'DIVERTED',  'mean'),
            ( 'DIVERTED',   'max'),
            ( 'DIVERTED',   'sum')],
           )

In [68]:
a.columns.get_level_values(0)

Index(['CANCELLED', 'CANCELLED', 'CANCELLED', 'DIVERTED', 'DIVERTED',
       'DIVERTED'],
      dtype='str')

In [69]:
a.columns.get_level_values(1)

Index(['min', 'max', 'count', 'mean', 'max', 'sum'], dtype='str')

In [70]:
a.columns.get_level_values(2)

IndexError: Too many levels: Index has only 2 levels, not 3

In [71]:
a.columns.to_flat_index()

Index([  ('CANCELLED', 'min'),   ('CANCELLED', 'max'), ('CANCELLED', 'count'),
         ('DIVERTED', 'mean'),    ('DIVERTED', 'max'),    ('DIVERTED', 'sum')],
      dtype='object')

In [76]:
for x, y in a.columns.to_flat_index():
    print(f'{x}_{y}')

CANCELLED_min
CANCELLED_max
CANCELLED_count
DIVERTED_mean
DIVERTED_max
DIVERTED_sum

In [77]:
a.columns = for x, y in a.columns.to_flat_index():
    print(f'{x}_{y}')

SyntaxError: invalid syntax (764655993.py, line 1)

In [78]:
a.columns = [f'{x}_{y}' for x, y in a.columns.to_flat_index()]

In [82]:
a.to_csv('result.csv')

In [86]:
a = a.reset_index()

In [88]:
a.to_csv('result.csv', index=False)

In [ ]:
flights.groupby(['AIRLINE', 'WEEKDAY'])\
    .agg(cancelled_min = ('CANCELLED','min'), 
         cancelled_max = ('CANCELLED', 'max'))

                 cancelled_min  cancelled_max
AIRLINE WEEKDAY
AA      1                    0              1
        2                    0              1
        3                    0              1
        4                    0              1
        5                    0              1
...                        ...            ...
WN      3                    0              1
        4                    0              1
        5                    0              1
        6                    0              1
        7                    0              1

[98 rows x 2 columns]

In [90]:
flights.groupby(['AIRLINE', 'WEEKDAY'])\
    .agg(cancelled_min = pd.NamedAgg('CANCELLED','min'), 
         cancelled_max = pd.NamedAgg('CANCELLED', 'max'))

                 cancelled_min  cancelled_max
AIRLINE WEEKDAY
AA      1                    0              1
        2                    0              1
        3                    0              1
        4                    0              1
        5                    0              1
...                        ...            ...
WN      3                    0              1
        4                    0              1
        5                    0              1
        6                    0              1
        7                    0              1

[98 rows x 2 columns]

In [93]:
weight_loss = pd.read_csv('data/weight_loss.csv')
weight_loss.head()

  Name Month    Week  Weight
0  Bob   Jan  Week 1     291
1  Amy   Jan  Week 1     197
2  Bob   Jan  Week 2     288
3  Amy   Jan  Week 2     189
4  Bob   Jan  Week 3     283

In [96]:
weight_loss.tail()

   Name Month    Week  Weight
27  Amy   Apr  Week 2     164
28  Bob   Apr  Week 3     253
29  Amy   Apr  Week 3     164
30  Bob   Apr  Week 4     250
31  Amy   Apr  Week 4     161

In [95]:
weight_loss.groupby('Name').agg({"Weight":['first', 'last']})

     Weight
      first last
Name
Amy     197  161
Bob     291  250

In [97]:
weight_loss.groupby('Name').agg({'Weight':'sqrt_mean'})

AttributeError: 'SeriesGroupBy' object has no attribute 'sqrt_mean'

In [98]:
def sqrt_mean(series):
    positive_values = [x ** 0.5 for x in series if x >= 0]
    return sum(positive_values) / len(positive_values) if positive_values else None

In [ ]:
weight_loss.groupby('Name').agg({'Weight': sqrt_mean})

         Weight
Name
Amy   13.302696
Bob   16.438998

In [111]:
sqrt_mean([64])

8.0

In [104]:
c = pd.Series({'tst':[32, 54]})
type(c)

pandas.Series

In [112]:
s = pd.Series([0, 1, 1, 0, 1, 1, 1, 0])
s

0    0
1    1
2    1
3    0
4    1
5    1
6    1
7    0
dtype: int64

In [ ]:
s.cumsum()  # running total

0    0
1    1
2    2
3    2
4    3
5    4
6    5
7    5
dtype: int64

In [114]:
weight_loss.groupby('Name')['Weight'].cumsum()

0      291
1      197
2      579
3      386
4      862
5      575
6     1145
7      765
8     1428
9      955
10    1703
11    1139
12    1971
13    1316
14    2239
15    1489
16    2507
17    1662
18    2778
19    1835
20    3043
21    2005
22    3304
23    2175
24    3565
25    2345
26    3823
27    2509
28    4076
29    2673
30    4326
31    2834
Name: Weight, dtype: int64

In [115]:
weight_loss.groupby('Name').agg({'Weight':'cumsum'})

    Weight
0      291
1      197
2      579
3      386
4      862
5      575
6     1145
7      765
8     1428
9      955
10    1703
11    1139
12    1971
13    1316
14    2239
15    1489
16    2507
17    1662
18    2778
19    1835
20    3043
21    2005
22    3304
23    2175
24    3565
25    2345
26    3823
27    2509
28    4076
29    2673
30    4326
31    2834

In [117]:
sales_data = pd.read_csv('data/sales_data.csv')
sales_data

          Date                 Product     Category  Quantity  Price
0   2023-01-01                  Laptop  Electronics        10    800
1   2023-01-01                 T-Shirt     Clothing         5     20
2   2023-01-02              Smartphone  Electronics         8    400
3   2023-01-02            Coffee Maker         Home        12     50
4   2023-01-03                   Jeans     Clothing        15     30
5   2023-01-03                 Blender         Home         6     60
6   2023-01-04              Headphones  Electronics        10    150
7   2023-01-04                 Sweater     Clothing         7     35
8   2023-01-05                 Toaster         Home         8     25
9   2023-01-05                  Tablet  Electronics        12    300
10  2023-01-06                Sneakers     Clothing        10     50
11  2023-01-06          Vacuum Cleaner         Home         5     80
12  2023-01-07                Smart TV  Electronics        15   1000
13  2023-01-07                  Hoodie     Clothing         6     25
14  2023-01-08          Blu-ray Player         Home         9     70
15  2023-01-08        Wireless Earbuds  Electronics        11    120
16  2023-01-09            Denim Jacket     Clothing        13     45
17  2023-01-09            Air Purifier         Home         7     90
18  2023-01-10          Gaming Console  Electronics        14    400
19  2023-01-10            Formal Shirt     Clothing         8     35
20  2023-01-11            Cookware Set         Home        10     60
21  2023-01-11     External Hard Drive  Electronics         9     80
22  2023-01-12              Sunglasses     Clothing        11     15
23  2023-01-12               Desk Lamp         Home         6     25
24  2023-01-13        Wireless Speaker  Electronics        12     70
25  2023-01-13              Sweatpants     Clothing         7     20
26  2023-01-14            Coffee Table         Home         8    100
27  2023-01-14                   Drone  Electronics        10    300
28  2023-01-15                Backpack     Clothing        14     40
29  2023-01-15           Comforter Set         Home         7     45
30  2023-01-16         Fitness Tracker  Electronics         9     60
31  2023-01-16            Casual Shoes     Clothing         6     30
32  2023-01-17           Kitchen Scale         Home        12     20
33  2023-01-17               Projector  Electronics        13    200
34  2023-01-18             Dress Shirt     Clothing         8     25
35  2023-01-18              Steam Iron         Home        11     30
36  2023-01-19                Soundbar  Electronics        15    150
37  2023-01-19              Sweatshirt     Clothing         7     35
38  2023-01-20            Bedside Lamp         Home        10     20
39  2023-01-20  Point-and-Shoot Camera  Electronics         8    250
40  2023-01-21             Sport Shoes     Clothing        12     40
41  2023-01-21              Desk Chair         Home         6     75
42  2023-01-22          Wireless Mouse  Electronics        11     25
43  2023-01-22            Summer Dress     Clothing         9     30
44  2023-01-23         Pressure Cooker         Home        14     50
45  2023-01-23       Bluetooth Headset  Electronics         7     50
46  2023-01-24             Denim Skirt     Clothing         8     25
47  2023-01-24               Bookshelf         Home        13     80
48  2023-01-25              4K Monitor  Electronics         9    350
49  2023-01-25             Cargo Pants     Clothing        11     30

You are given a dataset containing sales data for an e-commerce website. The dataset (`task\sales_data.csv`) has the following columns:

- `Date`: Date of the sale.
- `Product`: Name of the product sold.
- `Category`: Category to which the product belongs.
- `Quantity`: Number of units sold.
- `Price`: Price per unit.

**Tasks:**

1. Group the data by the `Category` column and calculate the following aggregate statistics for each category:
   - Total quantity sold.
   - Average price per unit.

In [122]:
sales_data.groupby('Category').agg({'Quantity':'sum', 'Price':'mean'}).round(1)

             Quantity  Price
Category
Clothing          157   31.2
Electronics       183  276.8
Home              144   55.0

In [124]:
sales_data['Total_Sales'] = sales_data['Quantity'] * sales_data['Price']

In [128]:
sales_data

,Date,Product,Category,Quantity,Price,Total_Sales
0,2023-01-01,Laptop,Electronics,10,800,8000
1,2023-01-01,T-Shirt,Clothing,5,20,100
2,2023-01-02,Smartphone,Electronics,8,400,3200
3,2023-01-02,Coffee Maker,Home,12,50,600
4,2023-01-03,Jeans,Clothing,15,30,450
5,2023-01-03,Blender,Home,6,60,360
6,2023-01-04,Headphones,Electronics,10,150,1500
7,2023-01-04,Sweater,Clothing,7,35,245
8,2023-01-05,Toaster,Home,8,25,200
9,2023-01-05,Tablet,Electronics,12,300,3600
10,2023-01-06,Sneakers,Clothing,10,50,500
11,2023-01-06,Vacuum Cleaner,Home,5,80,400
12,2023-01-07,Smart TV,Electronics,15,1000,15000
13,2023-01-07,Hoodie,Clothing,6,25,150
14,2023-01-08,Blu-ray Player,Home,9,70,630
15,2023-01-08,Wireless Earbuds,Electronics,11,120,1320
16,2023-01-09,Denim Jacket,Clothing,13,45,585
17,2023-01-09,Air Purifier,Home,7,90,630
18,2023-01-10,Gaming Console,Electronics,14,400,5600
19,2023-01-10,Formal Shirt,Clothing,8,35,280
20,2023-01-11,Cookware Set,Home,10,60,600
21,2023-01-11,External Hard Drive,Electronics,9,80,720
22,2023-01-12,Sunglasses,Clothing,11,15,165
23,2023-01-12,Desk Lamp,Home,6,25,150
24,2023-01-13,Wireless Speaker,Electronics,12,70,840
25,2023-01-13,Sweatpants,Clothing,7,20,140
26,2023-01-14,Coffee Table,Home,8,100,800
27,2023-01-14,Drone,Electronics,10,300,3000
28,2023-01-15,Backpack,Clothing,14,40,560
29,2023-01-15,Comforter Set,Home,7,45,315
30,2023-01-16,Fitness Tracker,Electronics,9,60,540
31,2023-01-16,Casual Shoes,Clothing,6,30,180
32,2023-01-17,Kitchen Scale,Home,12,20,240
33,2023-01-17,Projector,Electronics,13,200,2600
34,2023-01-18,Dress Shirt,Clothing,8,25,200
35,2023-01-18,Steam Iron,Home,11,30,330
36,2023-01-19,Soundbar,Electronics,15,150,2250
37,2023-01-19,Sweatshirt,Clothing,7,35,245
38,2023-01-20,Bedside Lamp,Home,10,20,200
39,2023-01-20,Point-and-Shoot Camera,Electronics,8,250,2000
40,2023-01-21,Sport Shoes,Clothing,12,40,480
41,2023-01-21,Desk Chair,Home,6,75,450
42,2023-01-22,Wireless Mouse,Electronics,11,25,275
43,2023-01-22,Summer Dress,Clothing,9,30,270
44,2023-01-23,Pressure Cooker,Home,14,50,700
45,2023-01-23,Bluetooth Headset,Electronics,7,50,350
46,2023-01-24,Denim Skirt,Clothing,8,25,200
47,2023-01-24,Bookshelf,Home,13,80,1040
48,2023-01-25,4K Monitor,Electronics,9,350,3150
49,2023-01-25,Cargo Pants,Clothing,11,30,330

In [ ]:
sales_data.iloc[sales_data.groupby('Category')['Quantity'].idxmax()]    # har bir category boyicha eng maximum sotilgan mahsulotlar soni

          Date          Product     Category  Quantity  Price  Total_Sales
4   2023-01-03            Jeans     Clothing        15     30          450
12  2023-01-07         Smart TV  Electronics        15   1000        15000
44  2023-01-23  Pressure Cooker         Home        14     50          700

In [137]:
sales_data.iloc[sales_data.groupby('Date')['Total_Sales'].idxmax()]['Date'].size

25