In [1]:
import pandas as pd 

customers = pd.read_csv('data/olist_customers_dataset.csv')

customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [4]:
customers.groupby('customer_state', as_index=False).agg({'customer_zip_code_prefix': ['sum', 'count']})

   customer_state customer_zip_code_prefix
                                       sum  count
0              AC                  5663083     81
1              AL                 23630159    413
2              AM                 10223610    148
3              AP                  4685883     68
4              BA                149065184   3380
5              CE                 82324183   1336
6              DF                153364503   2140
7              ES                 59561415   2033
8              GO                151484987   2020
9              MA                 48806379    747
10             MG                409683996  11635
11             MS                 56728872    715
12             MT                 71098060    907
13             PA                 65648990    975
14             PB                 31234533    536
15             PE                 88671796   1652
16             PI                 31801254    495
17             PR                425049519   5045
18             RJ                307996134  12852
19             RN                 28754681    485
20             RO                 19449863    253
21             RR                  3188234     46
22             RS                517894780   5466
23             SC                323032976   3637
24             SE                 17217716    350
25             SP                386165343  41746
26             TO                 21679437    280

In [7]:
products = pd.read_csv('data/olist_products_dataset.csv')
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [8]:
orders = pd.read_csv('data/olist_orders_dataset.csv')
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [9]:
order_items = pd.read_csv('data/olist_order_items_dataset.csv')

order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [10]:
product_category_name = pd.read_csv('data/product_category_name_translation.csv')
product_category_name

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [23]:
result = (
    order_items
    .merge(products, on='product_id')
    .merge(product_category_name, on='product_category_name')
    .merge(orders, on='order_id')
)

cancelled = (
    result[result['order_status'] == 'canceled']
    .groupby('product_category_name_english', as_index=False)
    .agg(cancelled_orders=('order_status', 'count'))
    .sort_values('cancelled_orders', ascending=False)
)

cancelled

              product_category_name_english  cancelled_orders
41                           sports_leisure                51
32                               housewares                49
8                     computers_accessories                46
28                            health_beauty                36
25                          furniture_decor                36
44                                     toys                34
3                                      auto                30
45                            watches_gifts                21
4                                      baby                20
27                             garden_tools                19
43                                telephony                18
5                            bed_bath_table                18
13                               cool_stuff                16
38                                perfumery                15
42                               stationery                12
36                      musical_instruments                11
18                              electronics                11
9                            consoles_games                10
40                         small_appliances                 8
6                    books_general_interest                 7
19                 fashion_bags_accessories                 6
12                construction_tools_safety                 5
39                                 pet_shop                 5
14                 costruction_tools_garden                 4
34                      luggage_accessories                 4
22                          fixed_telephony                 3
30                        home_appliances_2                 3
0                          air_conditioning                 2
11                construction_tools_lights                 2
10          construction_tools_construction                 2
33  kitchen_dining_laundry_garden_furniture                 2
29                          home_appliances                 2
24                               food_drink                 2
17                             dvds_blu_ray                 2
21                            fashion_shoes                 2
26                    furniture_living_room                 2
1                                       art                 1
2                                     audio                 1
7                        christmas_supplies                 1
15                      diapers_and_hygiene                 1
16                                   drinks                 1
20                    fashion_male_clothing                 1
23                                     food                 1
37                         office_furniture                 1
31                        home_construction                 1
35                             market_place                 1

In [19]:
product_category_name.dtypes

product_category_name            str
product_category_name_english    str
dtype: object

In [20]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [ ]:
import sqlite3

conn = sqlite3.connect('data/chinook.db')

artists = pd.read_sql("SELECT *FROM artists", conn)

albums = pd.read_sql("SELECT *FROM albums", conn)

full_version = (
    albums
    .merge(artists, on='ArtistId')
)

full_version['full_version'] = (
    full_version['Title'] + ' by ' + full_version['Name']
)

full_version[['full_version']]

conn.close()

                                          full_version
0       For Those About To Rock We Salute You by AC/DC
1                          Balls to the Wall by Accept
2                          Restless and Wild by Accept
3                           Let There Be Rock by AC/DC
4                                Big Ones by Aerosmith
..                                                 ...
342           Respighi:Pines of Rome by Eugene Ormandy
343  Schubert: The Late String Quartets & String Qu...
344  Monteverdi: L'Orfeo by C. Monteverdi, Nigel Ro...
345             Mozart: Chamber Music by Nash Ensemble
346  Koyaanisqatsi (Soundtrack from the Motion Pict...

[347 rows x 1 columns]